import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import Card from "../components/Card";

export default function Home({ states }) {
  const [stateId, setStateId] = useState(1);
  const [districts, setDistricts] = useState([]);
  const [districtId, setDistrictId] = useState(1);
  const [centres, setCentres] = useState([]);
  const [pincode, setPincode] = useState("");

  function getDate() {
    var today = new Date();
    var dd = String(today.getDate()).padStart(2, "0");
    var mm = String(today.getMonth() + 1).padStart(2, "0"); //January is 0!
    var yyyy = today.getFullYear();
    today = dd + "-" + mm + "-" + yyyy;
    return today;
  }

  useEffect(() => {
    getDate();
    axios
      .get(
        `https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict?district_id=${districtId}&date=${getDate()}`
      )
      .then((res) => {
        setCentres(res.data.sessions);
      });
  }, [stateId, districtId]);
  useEffect(() => {
    axios
      .get(
        `https://cdn-api.co-vin.in/api/v2/admin/location/districts/${stateId}`
      )
      .then((res) => {
        setDistricts(res.data.districts);
      });
  }, [stateId]);
  return (
    <div className="flex flex-col items-center py-10 space-y-5 ">
      <Head>
        <title>Covid Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className="animate-bounce	 sm:text-6xl text-3xl text-center font-bold">
        Covid Vaccination Checker
      </p>
      <span className="text-xs">By @densec</span>
      <div>
        <p className="sm:text-base text-xs">select your state</p>
        <select
          className="sm:text-base text-xs px-5 py-3 border"
          onChange={(e) => setStateId(e.target.value)}
          name=""
          id=""
        >
          {states?.map((state, index) => (
            <option key={index} value={`${state.state_id}`}>
              {state.state_name}
            </option>
          ))}
        </select>
      </div>

      <div>
        <h1 className="sm:text-base text-xs">Districts</h1>
        <select
          className="sm:text-base text-xs px-5 py-3 border"
          onChange={(e) => setDistrictId(e.target.value)}
          name=""
          id=""
        >
          {districts?.map((d, index) => (
            <option key={index} value={`${d.district_id}`}>
              {d.district_name}
            </option>
          ))}
        </select>
      </div>
      <input
        type="text"
        value={pincode}
        onChange={(e) => setPincode(e.target.value)}
        className="sm:text-base text-xs px-5 py-3 border"
        placeholder="search by pincode"
      />
      {centres.length > 0 ? (
        <div
          style={{ display: `${districtId && stateId ? "grid" : "hidden"}` }}
          className="sm:text-base text-xs grid-cols-2 sm:grid-cols-3"
        >
          {centres
            ?.filter((c) => {
              if (pincode === "") {
                return c;
              } else if (c.pincode.toString().includes(pincode)) {
                return c;
              } else {
                return 0;
              }
            })
            .map((c, index) => (
              <Card key={index} c={c} />
            ))}
        </div>
      ) : (
        <div className="">
          <p className="">NotAvailable 😢</p>
        </div>
      )}
    </div>
  );
}

export async function getStaticProps() {
  const statesRes = await fetch(
    "https://cdn-api.co-vin.in/api/v2/admin/location/states",
    {
      method: "GET",
      headers: {
        "User-Agent": "*",
        Accept: "application/json; charset=UTF-8",
      },
    }
  );
  const States = await statesRes.json();
  return {
    props: {
      states: States.states,
    },
  };
}
