import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Dropdown } from "semantic-ui-react";
import Card from "../components/Card";

export default function Home() {
  const [stateId, setStateId] = useState(0);
  const [districts, setDistricts] = useState([]);
  const [districtId, setDistrictId] = useState(0);
  const [centres, setCentres] = useState([]);
  const [pincode, setPincode] = useState("");
  const [States, setStates] = useState([]);

  function getDate() {
    var today = new Date();
    var dd = String(today.getDate()).padStart(2, "0");
    var mm = String(today.getMonth() + 1).padStart(2, "0"); //January is 0!
    var yyyy = today.getFullYear();
    today = dd + "-" + mm + "-" + yyyy;
    return today;
  }

  useEffect(() => {
    const structureState = async () => {
      const res = await axios.get(
        "https://cdn-api.co-vin.in/api/v2/admin/location/states"
      );
      console.log(res);
      const data = await res.data.states?.map((s) => ({
        key: s.state_id,
        value: s.state_id,
        text: s.state_name,
      }));
      setStates(data);
    };
    structureState();
  }, []);

  useEffect(() => {
    getDate();
    axios
      .get(
        `https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/findByDistrict?district_id=${districtId}&date=${getDate()}`
      )
      .then((res) => {
        setCentres(res.data.sessions);
      });
  }, [stateId, districtId]);

  useEffect(() => {
    async function fetchDistricts() {
      const res = await axios.get(
        `https://cdn-api.co-vin.in/api/v2/admin/location/districts/${stateId}`
      );
      const data = await res?.data?.districts.map((d) => ({
        key: d.district_id,
        value: d.district_id,
        text: d.district_name,
      }));
      setDistricts(data);
    }
    fetchDistricts();
  }, [stateId]);

  return (
    <div className="flex flex-col items-center py-10 space-y-5 ">
      <Head>
        <title>Covid Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <p className="sm:text-6xl text-3xl text-center font-bold">
        Covid Vaccination Checker
      </p>

      <div>
        <Dropdown
          onChange={(e, data) => setStateId(data.value)}
          placeholder="State"
          selection
          options={States}
        />
      </div>

      <div>
        <Dropdown
          onChange={(e, data) => setDistrictId(data.value)}
          placeholder="Districts"
          selection
          options={districts}
        />
      </div>
      <input
        type="number"
        value={pincode}
        onChange={(e) => setPincode(e.target.value)}
        className="sm:text-base text-xs px-7 py-3 border"
        placeholder="search by pincode"
      />
      {centres.length > 0 ? (
        <div
          style={{ display: `${districtId && stateId ? "grid" : "hidden"}` }}
          className="sm:text-base text-xs grid-cols-2 sm:grid-cols-3"
        >
          {centres
            ?.filter((c) => {
              if (pincode === "") {
                return c;
              } else if (c.pincode.toString().includes(pincode)) {
                return c;
              } else {
                return 0;
              }
            })
            .map((c, index) => (
              <Card key={index} c={c} />
            ))}
        </div>
      ) : (
        <div className="">
          <p className="">NotAvailable 😢</p>
        </div>
      )}
    </div>
  );
}
